version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: app-nginx
    hostname: app-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/html/index.html:/var/www/app/index.html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - go
    networks:
      local-net:
    restart: always

  go:
    build:
      context: ./
      dockerfile: ./docker/go/Dockerfile
    container_name: app-go
    hostname: app-go
    depends_on:
      - mysql
    networks:
      local-net:
    restart: always

  mysql:
    image: mysql:latest
    container_name: app-mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=demo_pass
      - MYSQL_ROOT_PASSWORD=demo_secret
    volumes:
        - "demo_mysql_volume:/var/lib/mysql"
        - "./docker/mysql/dump:/var/dump"
    networks:
      local-net:

networks:
  local-net:
    driver: bridge
    name: "local-net"

volumes:
  demo_mysql_volume:
    name: "demo_mysql_volume"