version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: app-mysql
        hostname: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=demo
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=mysql
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - "demo_mysql_volume:/var/lib/mysql"
            - "./dump:/var/www/dump"
        networks:
            - local-net

networks:
    local-net:
        external: true

volumes:
    demo_mysql_volume:
        name: "demo_mysql_volume"